export const CANVAS_CONTAINER_HEIGHT = 800;
export const CANVAS_CONTAINER_WIDTH = 1280;
export const CANVAS_SINGLE_BLOCK_WIDTH = 3000;
export const CANVAS_HORIZONTAL_SPACING = 250;
export const CANVAS_VERTICAL_SPACING = 220;
